apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s2555zh4i-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s2555zh4i-python 
  name: s2555zh4i-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s2555zh4i-python 
